baseURL = "/"
languageCode = "fr-FR"
defaultContentLanguage = "fr"
buildDrafts = true
canonifyURLs = false
uglyURLS = true
title = "Grepoguide"
theme = "learn"
themesdir = "themes"

[params]
  themeVariant = "red"
  editURL = "https://github.com/timothee-decoster/Grepoguide/edit/master/content/"
  description = "Documentation for Grepolis"
  author = "Timothée Decoster"

[outputs]
home = [ "HTML", "RSS", "JSON"]
